<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="Personal" failures="2" tests="16" name="Default test" time="16.71" errors="0" timestamp="09 Feb 2019 10:05:27 GMT">
  <testcase classname="parallel.testcases.TestFunctionalityB" name="testB_One" time="0.718"/>
  <testcase classname="parallel.testcases.TestFunctionalityB" name="testB_four" time="0.176"/>
  <testcase classname="parallel.testcases.TestFunctionalityB" name="testB_three" time="0.251">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at parallel.testcases.TestFunctionalityB.testB_three(TestFunctionalityB.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testB_three -->
  <testcase classname="parallel.testcases.TestFunctionalityB" name="testB_two" time="0.145">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at parallel.testcases.TestFunctionalityB.testB_two(TestFunctionalityB.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testB_two -->
  <testcase classname="parallel.testcases.TestFunctionalityA" name="testA_One" time="2.001"/>
  <testcase classname="parallel.testcases.TestFunctionalityA" name="testA_four" time="1.561"/>
  <testcase classname="parallel.testcases.TestFunctionalityA" name="testA_three" time="2.096"/>
  <testcase classname="parallel.testcases.TestFunctionalityA" name="testA_two" time="0.488"/>
  <testcase classname="parallel.testcases.TestFunctionalityD" name="testD_One" time="0.205"/>
  <testcase classname="parallel.testcases.TestFunctionalityD" name="testD_four" time="0.187"/>
  <testcase classname="parallel.testcases.TestFunctionalityD" name="testD_three" time="0.213"/>
  <testcase classname="parallel.testcases.TestFunctionalityD" name="testD_two" time="0.25"/>
  <testcase classname="parallel.testcases.TestFunctionalityC" name="testC_One" time="0.39"/>
  <testcase classname="parallel.testcases.TestFunctionalityC" name="testC_four" time="0.396"/>
  <testcase classname="parallel.testcases.TestFunctionalityC" name="testC_three" time="0.469"/>
  <testcase classname="parallel.testcases.TestFunctionalityC" name="testC_two" time="0.328"/>
  <testcase classname="utility.CommonTest" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="utility.CommonTest" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="utility.CommonTest" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="utility.CommonTest" name="@BeforeTest setupTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setupTest -->
  <testcase classname="utility.CommonTest" name="@BeforeTest setupTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setupTest -->
  <testcase classname="utility.CommonTest" name="@BeforeTest setupTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setupTest -->
</testsuite> <!-- Default test -->
